// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MinimumWage
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("stateName")]
        public string StateName { get; set; }

        [JsonProperty("minimumWage")]
        public long MinimumWage { get; set; }

        [JsonProperty("stateRate")]
        public long StateRate { get; set; }

        [JsonProperty("federalRate")]
        public double FederalRate { get; set; }

        [JsonProperty("tippedMinimum")]
        public long TippedMinimum { get; set; }

        [JsonProperty("usesFederalRate")]
        public bool UsesFederalRate { get; set; }

        [JsonProperty("note")]
        public object Note { get; set; }
    }
}
